[package]
name = "owl-mcp-server"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["lib/common", "lib/http-api-call", "lib/image-qa-online", "lib/web-search"]


[dependencies]


[workspace.dependencies]
chrono = "0.4.41"
anyhow = "1.0.97"
thiserror = "2.0"
log = "0.4.27"
env_logger = "0.11.8"
ansi_term = "0.12.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["rt-multi-thread"] }
reqwest = "0.12.15"
rmcp = { version = "0.3.0", features = ["server", "transport-io"] }
