[package]
name = "web-search"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../lib/common" }
anyhow = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rmcp = { workspace = true }
log = "0.4.27"
scraper = "0.23.1"
headless_chrome = "1.0.17"
openai_dive = { version = "1.0.1", features = ["stream"], git = "ssh://git@github.com/xgpxg/openai-client.git" }
clap = { version = "4.5", features = ["derive"] }
regex = "1.11.1"
rocket = "0.5"
sysinfo = "0.36"

[target.x86_64-unknown-linux-musl.dependencies]
openssl-sys = { version = "0.9", features = ["vendored"] }