[package]
name = "image-qa-online"
version = "0.1.0"
edition = "2024"

[dependencies]
openai_dive = "1.2.3"
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rmcp = { workspace = true }
[dev-dependencies]
base64 = "0.22.1"