[package]
name = "image-qa-online"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../../lib/common" }
anyhow = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rmcp = { workspace = true }
openai_dive = { version = "1.0.1", features = ["stream"], git = "ssh://git@github.com/xgpxg/openai-client.git" }
base64 = "0.22.1"
log = "0.4.27"


